/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComingSoonRouteImport } from './routes/coming-soon'
import { Route as GstInvoiceGeneratorRouteImport } from './routes/gst-invoice-generator'
import { Route as InvoiceSoftwareForFreelancersRouteImport } from './routes/invoice-software-for-freelancers'
import { Route as QuotationSoftwareRouteImport } from './routes/quotation-software'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComingSoonRoute = ComingSoonRouteImport.update({
  id: '/coming-soon',
  path: '/coming-soon',
  getParentRoute: () => rootRouteImport,
} as any)
const GstInvoiceGeneratorRoute = GstInvoiceGeneratorRouteImport.update({
  id: '/gst-invoice-generator',
  path: '/gst-invoice-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoiceSoftwareForFreelancersRoute =
  InvoiceSoftwareForFreelancersRouteImport.update({
    id: '/invoice-software-for-freelancers',
    path: '/invoice-software-for-freelancers',
    getParentRoute: () => rootRouteImport,
  } as any)
const QuotationSoftwareRoute = QuotationSoftwareRouteImport.update({
  id: '/quotation-software',
  path: '/quotation-software',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coming-soon': typeof ComingSoonRoute
  '/gst-invoice-generator': typeof GstInvoiceGeneratorRoute
  '/invoice-software-for-freelancers': typeof InvoiceSoftwareForFreelancersRoute
  '/quotation-software': typeof QuotationSoftwareRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coming-soon': typeof ComingSoonRoute
  '/gst-invoice-generator': typeof GstInvoiceGeneratorRoute
  '/invoice-software-for-freelancers': typeof InvoiceSoftwareForFreelancersRoute
  '/quotation-software': typeof QuotationSoftwareRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/coming-soon': typeof ComingSoonRoute
  '/gst-invoice-generator': typeof GstInvoiceGeneratorRoute
  '/invoice-software-for-freelancers': typeof InvoiceSoftwareForFreelancersRoute
  '/quotation-software': typeof QuotationSoftwareRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/coming-soon'
    | '/gst-invoice-generator'
    | '/invoice-software-for-freelancers'
    | '/quotation-software'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/coming-soon'
    | '/gst-invoice-generator'
    | '/invoice-software-for-freelancers'
    | '/quotation-software'
  id:
    | '__root__'
    | '/'
    | '/coming-soon'
    | '/gst-invoice-generator'
    | '/invoice-software-for-freelancers'
    | '/quotation-software'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComingSoonRoute: typeof ComingSoonRoute
  GstInvoiceGeneratorRoute: typeof GstInvoiceGeneratorRoute
  InvoiceSoftwareForFreelancersRoute: typeof InvoiceSoftwareForFreelancersRoute
  QuotationSoftwareRoute: typeof QuotationSoftwareRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coming-soon': {
      id: '/coming-soon'
      path: '/coming-soon'
      fullPath: '/coming-soon'
      preLoaderRoute: typeof ComingSoonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gst-invoice-generator': {
      id: '/gst-invoice-generator'
      path: '/gst-invoice-generator'
      fullPath: '/gst-invoice-generator'
      preLoaderRoute: typeof GstInvoiceGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoice-software-for-freelancers': {
      id: '/invoice-software-for-freelancers'
      path: '/invoice-software-for-freelancers'
      fullPath: '/invoice-software-for-freelancers'
      preLoaderRoute: typeof InvoiceSoftwareForFreelancersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotation-software': {
      id: '/quotation-software'
      path: '/quotation-software'
      fullPath: '/quotation-software'
      preLoaderRoute: typeof QuotationSoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComingSoonRoute: ComingSoonRoute,
  GstInvoiceGeneratorRoute: GstInvoiceGeneratorRoute,
  InvoiceSoftwareForFreelancersRoute: InvoiceSoftwareForFreelancersRoute,
  QuotationSoftwareRoute: QuotationSoftwareRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
